### ISSUE TITLE
Improving Undelegating Requests and Lifecycle

### ISSUE THREAD

**Issue by toliujiayi** [babylonchain/babylon#159]
## Summary

Right now the structure of Undelegating Requests and lifecycle events is a little too simple, which leads to numerous difficulties for implementing the explorer 

## Problem Definition

1. Undelegating requests right now don't have an id-like property associated with it, neither does unbonded events. This means that it is very hard to associate an unbonding request and an undelegating request
2. Two undelegating requests sent in the same epoch would only be responded by one unbonding event. This also makes implementing the paring algorithm event harder and more unclear.

## Proposal

We could either associate an ID with each undelegating request, and unbonded events would use the same id. Alternatively we could add the epoch number of the corresponding undelegating event of each unbonded event. Both ways would make the pairing process much simpler

**Comment by SebastianElvis** [comment]
Closing this issue since the backend/frontend does not need such IDs.
