### ISSUE TITLE
Validators should stop submitting BLS-sigs when they are syncing

### ISSUE THREAD

**Issue by gitferry** [babylonchain/babylon#182]
When a validator is syncing, it will relay all the history transactions including the ones sending BLS-sig transactions that have been sent already. It will cause unnecessary gas costs and unpredictable errors. So we should disable BLS submission when the validator is syncing.

**Comment by gitferry** [comment]
After some investigation, it seems that in the application layer (cosmos-sdk), we don't know whether the node (Tendermint) is syncing. This issue will be naturally solved after ABCI++ is upgraded as BLS signatures will be no longer in blocks as transactions. Should we close this issue now? cc @vitsalis

**Comment by vitsalis** [comment]
Yep, agreed. When do we expect ABCI++ to become available?

**Comment by gitferry** [comment]
It's a good question but tbh I'm not sure about that, especially given the recent drama that happened to Tendermint. But I found [this](https://github.com/cometbft/cometbft/discussions/357). It seems that ABCI 2.0 (ABCI++) would be in version `0.38.x`
