### ISSUE TITLE
Chain died on block 621

### ISSUE THREAD

**Issue by obajay** [babylonchain/babylon#302]
## Steps to Reproduce
```python
cd $HOME
git clone https://github.com/babylonchain/babylon
cd babylon
git checkout v0.5.0
make install

babylond init MOniker --chain-id bbn-test2

#Download Genesis
wget https://raw.githubusercontent.com/obajay/nodes-Guides/main/Babylon/genesis.json -O $HOME/.babylond/config/genesis.json

PEERS="c2db7e074a6ac1fba3c0faf3a06e1cc890473993@rpc.testnet.babylonchain.io:26656"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.babylond/config/config.toml

#Create a service file
sudo tee /etc/systemd/system/babylond.service > /dev/null <<EOF
[Unit]
Description=babylond
After=network-online.target

[Service]
User=$USER
ExecStart=$(which babylond) start
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload && sudo systemctl enable babylond
sudo systemctl restart babylond && sudo journalctl -u babylond -f -o cat
```

**Comment by vitsalis** [comment]
Thanks for the issue @obajay . The official deployment of the testnet happened today. Please follow the [documentation for starting a node](https://docs.babylonchain.io/docs/testnet/setup-node) and get back to us if the issue persists. A couple of comments for the steps to reproduce:
- The chain ID is `bbn-test1`
- You should use the appropriate configuration on the `app.toml` file to specify the btc network and btc tag that we are using. Please refer to the [networks page](https://github.com/babylonchain/networks) for seed nodes and the values to enter on the `app.toml` configuration in accordance with the docs.

**Comment by obajay** [comment]
> 

was able to run with the updated parameters. Can I get tokens to create a validator?
```bbn16d9mgc3u6kz9q4xa8htxqjv5ekkslrwu25lm4g```
