### ISSUE TITLE
Broken link for testnet in the main README.md

### ISSUE THREAD

**Issue by kunallimaye** [babylonchain/babylon#403]
## Summary of Bug

The link the [Joining the testnet](https://github.com/babylonchain/babylon?tab=readme-ov-file#joining-the-testnet) section lands the user at [this page](https://docs.babylonchain.io/docs/testnet/overview) which is not available.  
The correct link seems to be [this](https://docs.babylonchain.io/docs/user-guides/btc-timestamping-testnet/overview)(?).

Simple doc change, doesn't require testing.

## Version
- [v0.7.2](https://github.com/babylonchain/babylon/releases/tag/v0.7.2).

**Comment by kunallimaye** [comment]
[PR](https://github.com/babylonchain/babylon/pull/404)

**Comment by SebastianElvis** [comment]
Closed in favour of https://github.com/babylonchain/babylon/pull/404
