### ISSUE TITLE
Dead Link in the Git "Joining the testnet" 

### ISSUE THREAD

**Issue by Benji35450** [babylonchain/babylon#406]
![image](https://github.com/babylonchain/babylon/assets/34221702/a69ecad0-43a0-4840-820c-89beb0e3485c)

Joining the testnet
Please follow the instructions on the [Joining the Testnet documentation page](https://docs.babylonchain.io/docs/user-guides/btc-timestamping-testnet/overview).

Have a great day

**Comment by vitsalis** [comment]
The link seems to be working for me.
