### ISSUE TITLE
xxx_validator.info: key not found

### ISSUE THREAD

**Issue by big-zak** [babylonchain/babylon#454]
## Summary of Bug

Activating the validator give me an error: xxx_validator.info: key not found

## Version

v0.7.2

## Steps to Reproduce

run the command below where xxx_validator is the name of the keystring

```
babylond tx checkpointing create-validator \
    --amount="1000000ubbn" \
    --pubkey=$(babylond tendermint show-validator) \
    --moniker="XXX Validator" \
    --chain-id="bbn-test-2" \
    --gas="auto" \
    --gas-adjustment=1.2 \
    --gas-prices=0.0025ubbn \
    --keyring-backend="test" \
    --from="xxx_validator" \
    --commission-rate="0.10" \
    --commission-max-rate="0.20" \
    --commission-max-change-rate="0.01" \
    --min-self-delegation="1"

```

**Comment by SebastianElvis** [comment]
Hi there, have you ensured the following items?

- `babylond` is using the correct home directory (you can use `--home` flag to specify it if unsure)
- `xxx_validator.info` exists underthe home directory
