### ISSUE TITLE
Is there a support of rest API?

### ISSUE THREAD

**Issue by VAIBHAVJINDAL3012** [babylonchain/babylon#497]
Hi team
I was going through the project, I couldn't find the API section.
Do we have a support for it?

**Comment by SebastianElvis** [comment]
Hi, Babylon is based on Cosmos SDK so natively supports Cosmos SDK / CometBFT APIs. See https://docs.cosmos.network/v0.50/learn/advanced/grpc_rest for the instructions.

In addition, Babylon implements APIs for BTC staking/timestamping protocols. Please refer to `query.proto` files under https://github.com/babylonchain/babylon/tree/dev/proto for the API spec

**Comment by VAIBHAVJINDAL3012** [comment]
Yes, I think it still need to have the API folder even if it follows the cosmos?

**Comment by SebastianElvis** [comment]
Do you mean this folder https://github.com/babylonchain/babylon/tree/dev/proto/babylon ?

**Comment by VAIBHAVJINDAL3012** [comment]
https://github.com/cosmos/cosmos-sdk/tree/main/api
This folder
