### ISSUE TITLE
Error: Object does not exist at path “/”`

### ISSUE THREAD

**Issue by a3165458** [babylonchain/babylon#498]
root@vmi1618937:~# babylond keys add wallet
Error: Object does not exist at path “/”
Usage:
  babylond keys add <name> [flags]

Flags:
      --account uint32           Account number for HD derivation (less than equal 2147483647)
      --coin-type uint32         coin type number for HD derivation (default 118)
      --dry-run                  Perform action, but don't add key to local keystore
      --hd-path string           Manual HD Path derivation (overrides BIP44 config)
  -h, --help                     help for add
      --index uint32             Address index number for HD derivation (less than equal 2147483647)
  -i, --interactive              Interactively prompt user for BIP39 passphrase and mnemonic
      --key-type string          Key signing algorithm to generate keys for (default "secp256k1")
      --ledger                   Store a local reference to a private key on a Ledger device
      --multisig strings         List of key names stored in keyring to construct a public legacy multisig key
      --multisig-threshold int   K out of N required signatures. For use in conjunction with --multisig (default 1)
      --no-backup                Don't print out seed phrase (if others are watching the terminal)
      --nosort                   Keys passed to --multisig are taken in the order they're supplied
      --pubkey string            Parse a public key in JSON format and saves key info to <name> file.
      --pubkey-base64 string     Parse a public key in base64 format and saves key info.
      --recover                  Provide seed phrase to recover existing key instead of creating

Global Flags:
      --home string              directory for config and data (default "/root/.babylond")
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --log_format string        The logging format (json|plain) (default "plain")
      --log_level string         The logging level (trace|debug|info|warn|error|fatal|panic|disabled or '*:<level>,<key>:<level>') (default "info")
      --log_no_color             Disable colored logs
      --output string            Output format (text|json) (default "text")
      --trace                    print out full stack trace on errors

2:17AM ERR failure when running app err="Object does not exist at path “/”"

**Comment by SebastianElvis** [comment]
The command works from my side. Which version of Babylon are you using and could you please provide your setup (OS, system spec, etc..)? Thank you

**Comment by a3165458** [comment]
Hi:

**Comment by Pitchanai** [comment]
I found this problem too
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```
