### ISSUE TITLE
An error occurred when checking balance

### ISSUE THREAD

**Issue by a3165458** [babylonchain/babylon#499]
root@vmi1659051:~# babylond q bank balances bbn16z9wvargv8etm2k8tmpppg5z57k6wwwqe50pqr 

Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = invalid address: invalid Bech32 prefix; expected art, got bbn: invalid request

**Comment by SebastianElvis** [comment]
Hi, which version of Babylon are you using? `bbn` is supposed to be the right account prefix but the error message says the node expects something else i.e., `art`

**Comment by a3165458** [comment]
I am using version 0.8.3 of babylon. Since I have other applications occupying port 26657, I modified the port of babylon. Babylon’s current synchronization block height and other functions are normal. Similar errors will occur when using functions such as balance query, block synchronization query (babylond status | jq .sync_info), and operations such as creating a validator.

**Comment by vitsalis** [comment]
This probably involves querying the wrong chain.
