### ISSUE TITLE
the "out of gas" reporting seemed to be wrong

### ISSUE THREAD

**Issue by kevinedu789** [babylonchain/babylon#504]
## Summary of Bug
The "out of gas" reporting seemed to be wrong during sync. 

## Version
v0.8.3

## Steps to Reproduce

1. Following the guide to set up a node for the Babylon system
https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/setup-node
2. Have a full node setup and synced.  I found the number of gas is reported wrong in my environment: 

ERR panic recovered in runTx err="out of gas in location: WriteFlat; gasWanted: 86056, gasUsed: 87080: out of gas" module=server

As you can see, the used gas 87080 is enough for the wanted gas 86056, so the "out of gas" reporting seemed to be wrong.##

**Comment by sbidolach** [comment]
I have this same issue 

```
ERR panic recovered in runTx err="out of gas in location: WritePerByte; gasWanted: 112156, gasUsed: 112614: out of gas" module=server
```

Have you solved it?

**Comment by vitsalis** [comment]
This happened in a prior version and should now be resolved.
