### ISSUE TITLE
please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction

### ISSUE THREAD

**Issue by CockyCat** [babylonchain/babylon#506]
systemctl start babylond.service & sudo journalctl -u babylond.service -f --no-hostname -o cat, always show :
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824635291200})

**Comment by VAIBHAVJINDAL3012** [comment]
Please check your genesis file, it should contain atleast one validator with delegation power greater than DefaultPowerReduction.
Are you running a devnet?

**Comment by CockyCat** [comment]
Thanks 4 your answer, How to get that atleast one validator with delegation power greater than DefaultPowerReduction  ?

Im running a test-net-3.

**Comment by vitsalis** [comment]
Please retrieve the genesis file from [here](https://github.com/babylonchain/networks/blob/main/bbn-test-3/genesis.tar.bz2) and follow the instructions here: https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/setup-node

**Comment by CockyCat** [comment]
> Please retrieve the genesis file from [here](https://github.com/babylonchain/networks/blob/main/bbn-test-3/genesis.tar.bz2) and follow the instructions here: https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/setup-node

When i upgraded v0.8.5, and  run this:

```
wget https://github.com/babylonchain/networks/raw/main/bbn-test-3/genesis.tar.bz2
tar -xjf genesis.tar.bz2 && rm genesis.tar.bz2
mv genesis.json ~/.babylond/config/genesis.json
```

last, I start service and also show this panic: 

12:06AM INF Closing snapshots/metadata.db module=server
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824640379552})
goroutine 1 [running]:
github.com/babylonchain/babylon/app.(*BabylonApp).InitChainer(_, {{0x3ca4c08, 0x5b3c4a0}, {0x3cc1b10, 0xc001546840}, {{0x0, 0x0}, {0xc00278aaa0, 0xa}, 0x0, ...}, ...}, ...)
