### ISSUE TITLE
"unknown flag: --amount" reported during creating validator

### ISSUE THREAD

**Issue by kevinedu789** [babylonchain/babylon#507]
Summary of Bug
"unknown flag: --amount" is reported during creating validator. 

Version
v0.8.3

Steps to Reproduce
1. Following the guide to set up a node for the Babylon system
https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/setup-node

2. You can see "unknown flag: --amount" is reported when creating validator 
ubuntu@VM-0-16-ubuntu:~$ babylond tx checkpointing create-validator --amount 1000000ubbn
--pubkey $(babylond tendermint show-validator)
--moniker "LINKNODE3"
--details "A_Babylon_Test_3_Node"
--website ""
--chain-id bbn-test-3
--commission-rate 0.05
--commission-max-rate 0.20
--commission-max-change-rate 0.01
--min-self-delegation 1
--from wallet
--gas-adjustment 1.4
--gas auto
--gas-prices 0.00001ubbn
-y
Error: unknown flag: --amount
Usage:
babylond tx checkpointing create-validator [path/to/validator.json] [flags]

Examples:
$ babylond tx staking create-validator path/to/validator.json --from keyname

Where validator.json contains:

{
"pubkey": {"@type":"/cosmos.crypto.ed25519.PubKey","key":"oWg2ISpLF405Jcm2vXV+2v4fnjodh6aafuIdeoW+rUw="},
"amount": "1000000stake",
"moniker": "myvalidator",
"identity": "optional identity signature (ex. UPort or Keybase)",
"website": "validator's (optional) website",
"security": "validator's (optional) security contact email",
"details": "validator's (optional) details",
"commission-rate": "0.1",
"commission-max-rate": "0.2",
"commission-max-change-rate": "0.01",
"min-self-delegation": "1"
}

where we can get the pubkey using "babylond tendermint show-validator"

Flags:
-a, --account-number uint The account number of the signing account (offline mode only)
--aux Generate aux signer data instead of sending a tx
-b, --broadcast-mode string Transaction broadcasting mode (sync|async) (default "sync")
--chain-id string The network chain ID
--dry-run ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
--fee-granter string Fee granter grants fees for the transaction
--fee-payer string Fee payer pays fees for the transaction instead of deducting from the signer
--fees string Fees to pay along with transaction; eg: 10uatom
--from string Name or address of private key with which to sign
--gas string gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can be used instead of "fees". (default 200000)
--gas-adjustment float adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored (default 1)
--gas-prices string Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
--generate-only Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
-h, --help help for create-validator
--home string The node home directory (default "/home/ubuntu/.babylond")
--ip string The node's public IP. It takes effect only when used in combination with --generate-only
--keyring-backend string Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
--keyring-dir string The client Keyring directory; if omitted, the default 'home' directory will be used
--ledger Use a connected Ledger device
--node string : to CometBFT rpc interface for this chain (default "tcp://localhost:26657")
--node-id string The node's ID
--note string Note to add a description to the transaction (previously --memo)
--offline Offline mode (does not allow any online functionality)
-o, --output string Output format (text|json) (default "json")
-s, --sequence uint The sequence number of the signing account (offline mode only)
--sign-mode string Choose sign mode (direct|amino-json|direct-aux|textual), this is an advanced feature
--timeout-height uint Set a block timeout height to prevent the tx from being committed past a certain height
--tip string Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
-y, --yes Skip tx broadcasting prompt confirmation

Global Flags:
--log_format string The logging format (json|plain) (default "plain")
--log_level string The logging level (trace|debug|info|warn|error|fatal|panic|disabled or '*:,:') (default "info")
--log_no_color Disable colored logs
--trace print out full stack trace on errors

4:10PM ERR failure when running app err="unknown flag: --amount"

**Comment by vitsalis** [comment]
The amount should be inserted in the `validator.json` file and not passed as a flag. Please view the instructions here: https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/become-validator
