### ISSUE TITLE
Node setup issue: post failed: Post "http://localhost:16457": dial tcp 127.0.0.1:16457: connect: connection refused

### ISSUE THREAD

**Issue by talentbuilder** [babylonchain/babylon#520]
## Summary of Bug
I setted up a node and ran well these days util today when I wanted to delegate some bbns to my node, i got  this error:
post failed: Post \"http://localhost:16457\": dial tcp 127.0.0.1:16457: connect: connection refused
<img width="950" alt="image" src="https://github.com/babylonchain/babylon/assets/10881940/c0ae0ad1-cf06-4058-8490-b5d86931bfa2">

I went to discord and found some others met this problem too, I don't know why, please help, many thanks.
<img width="409" alt="image" src="https://github.com/babylonchain/babylon/assets/10881940/deca3ad0-c995-4758-9cc0-6c7e7481c9f4">

## Version
0.8.3

## Steps to Reproduce
First run command "systemctl start babylond" to run the node, then run command "babylond status | jq" and get this error. In my case, port 16457 wasn't bond.

**Comment by a3165458** [comment]
don't change port ,babylond status need port 26657

**Comment by talentbuilder** [comment]
> don't change port ,babylond status need port 26657

Thank you for your reply. I just login in my server and the node's running well and can delegte now. But something I should say is that I do nothing about it and it recover by itself, I don't know why, so I guess if this situation is caused by the high load of network? because some others have the same problem in the same period when the pioneers campaign

**Comment by bfundac** [comment]
Yes, my port is 26657, and this error has also occurred. However, my automatic reply has not been successful yet, and I don't understand why the link was rejected at the moment

**Comment by macnyl001** [comment]
ERR Error dialing seed err="dial tcp 3.16.63.237:26656: connect: connection refused" module=p2p seed=9cb1974618ddd541c9a4f4562b842b96ffaf1446@3.16.63.237:26656
ERR Error dialing seed err="dial tcp 3.14.89.82:26656: connect: connection refused" module=p2p seed=49b4685f16670e784a0fe78f37cd37d56c7aff0e@3.14.89.82:26656
ERR Couldn't connect to any seeds module=p2p

**Comment by a3165458** [comment]
I speculate that it may be related to OOM being checked by the system process.

**Comment by a3165458** [comment]
> ERR Error dialing seed err="dial tcp 3.16.63.237:26656: connect: connection refused" module=p2p seed=9cb1974618ddd541c9a4f4562b842b96ffaf1446@3.16.63.237:26656 ERR Error dialing seed err="dial tcp 3.14.89.82:26656: connect: connection refused" module=p2p seed=49b4685f16670e784a0fe78f37cd37d56c7aff0e@3.14.89.82:26656 ERR Couldn't connect to any seeds module=p2p
> 
> how to fix these errors?

change peers

**Comment by macnyl001** [comment]
how to do it ?

**Comment by sbidolach** [comment]
I have the same error

```
6:24PM ERR failure when running app err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"
```

Have you been able to find a solution for this? It was working fine and when I checked today it seems that something is broken.

**Comment by sbidolach** [comment]
I found more logs. There is a problem running babylond at the moment.

```
Mar 03 18:28:43 vmi1685115.contaboserver.net cosmovisor[53471]: 6:28PM INF running app args=["start","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/ubuntu/.babylond/cosmovisor/genesi>
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF starting node with ABCI CometBFT in-process module=server
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=EventBus module=events msg="Starting EventBus service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF ABCI Handshake App Info hash=451F31B5334B25E2F322EFAAB2AADBB154F75C3A76C5081DD6E6184EEA814FBC height=61049 module=consensus pr>
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF ABCI Replay Blocks appHeight=61049 module=consensus stateHeight=61049 storeHeight=61050
Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF Replay last block using real app module=consensus
Mar 03 18:28:57 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM ERR panic recovered in runTx err="out of gas in location: WritePerByte; gasWanted: 112156, gasUsed: 112614: out of gas" module=ser>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF finalized block block_app_hash=6A002FB287CBE40F2323B949951941E73B40CEE52544A8D5B73D7019C1BF2DF3 height=61050 module=consensus >
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF executed block app_hash=6A002FB287CBE40F2323B949951941E73B40CEE52544A8D5B73D7019C1BF2DF3 height=61050 module=consensus
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF Closing application.db module=server
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF Closing snapshots/metadata.db module=server
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: panic: version does not exist
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: goroutine 1 [running]:
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/iavl.(*Store).Commit(0xc003328150?)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/iavl/store.go:127 +0xd7
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/rootmulti.commitStores(0xee7a, 0xc001d8b3e0, 0xc00237c420)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/rootmulti/store.go:1196 +0x158
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/rootmulti.(*Store).Commit(0xc001b4f000)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/rootmulti/store.go:482 +0x1a5
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00264e908)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:930 +0x2e2
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:56
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x20?, {0x3cadf08?, 0x5b444e0?}, 0xc03569bc48?)
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:113 +0xcd
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc001740000, {0x3cadf08, 0x5b444e0})
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:109 +0x168
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee7a, {{0xc>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/state/execution.go:393 +0x213
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee7a, {>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/state/execution.go:279 +0xfb0
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee79,>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:534 +0x24e
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:433 +0x77a
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc03569d3d8, {0x3cade60, 0xc00301caf0}, {0x3cce9b0, 0xc00121eb>
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x425
Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, ...}, ...)
```

**Comment by konbluesky** [comment]
> I found more logs. There is a problem running babylond at the moment.
> 
> ```
> Mar 03 18:28:43 vmi1685115.contaboserver.net cosmovisor[53471]: 6:28PM INF running app args=["start","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/ubuntu/.babylond/cosmovisor/genesi>
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF starting node with ABCI CometBFT in-process module=server
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=EventBus module=events msg="Starting EventBus service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF ABCI Handshake App Info hash=451F31B5334B25E2F322EFAAB2AADBB154F75C3A76C5081DD6E6184EEA814FBC height=61049 module=consensus pr>
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF ABCI Replay Blocks appHeight=61049 module=consensus stateHeight=61049 storeHeight=61050
> Mar 03 18:28:44 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM INF Replay last block using real app module=consensus
> Mar 03 18:28:57 vmi1685115.contaboserver.net cosmovisor[53483]: 6:28PM ERR panic recovered in runTx err="out of gas in location: WritePerByte; gasWanted: 112156, gasUsed: 112614: out of gas" module=ser>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF finalized block block_app_hash=6A002FB287CBE40F2323B949951941E73B40CEE52544A8D5B73D7019C1BF2DF3 height=61050 module=consensus >
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF executed block app_hash=6A002FB287CBE40F2323B949951941E73B40CEE52544A8D5B73D7019C1BF2DF3 height=61050 module=consensus
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF Closing application.db module=server
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: 6:29PM INF Closing snapshots/metadata.db module=server
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: panic: version does not exist
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: goroutine 1 [running]:
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/iavl.(*Store).Commit(0xc003328150?)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/iavl/store.go:127 +0xd7
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/rootmulti.commitStores(0xee7a, 0xc001d8b3e0, 0xc00237c420)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/rootmulti/store.go:1196 +0x158
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: cosmossdk.io/store/rootmulti.(*Store).Commit(0xc001b4f000)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         cosmossdk.io/store@v1.0.2/rootmulti/store.go:482 +0x1a5
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00264e908)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:930 +0x2e2
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:56
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x20?, {0x3cadf08?, 0x5b444e0?}, 0xc03569bc48?)
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:113 +0xcd
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc001740000, {0x3cadf08, 0x5b444e0})
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:109 +0x168
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee7a, {{0xc>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/state/execution.go:393 +0x213
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee7a, {>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/state/execution.go:279 +0xfb0
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, 0x1, 0xee79,>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:534 +0x24e
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:433 +0x77a
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc03569d3d8, {0x3cade60, 0xc00301caf0}, {0x3cce9b0, 0xc00121eb>
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]:         github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x425
> Mar 03 18:29:04 vmi1685115.contaboserver.net cosmovisor[53483]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc001d88ff8, 0x6}}, {0xc001d89020, 0xa}, ...}, ...)
> ```

I had same problem

**Comment by a3165458** [comment]
> how to do it ?

First use OOM detection to confirm whether this is the reason.
grep -i 'oom' /var/log/syslog
I have two devices running babylon, one with 16G RAM encountered this problem, and one with 64G RAM did not encounter this problem.

You can also try to use the swap function to optimize

sudo mkdir /swap
sudo fallocate -l 24G /swap/swapfile
sudo chmod 600 /swap/swapfile
sudo mkswap /swap/swapfile
sudo swapon /swap/swapfile
echo '/swap/swapfile swap swap defaults 0 0' >> /etc/fstab

**Comment by ThomasBlock** [comment]
i can confirm a growing RAM Problem. i guess it just restarted for me

![image](https://github.com/babylonchain/babylon/assets/43484940/7daac8f9-286a-49c5-bc0a-ebb69d5bb442)

but today it also crashed in a state where it will no longer boot up. what can i do?

`panic: version does not exist` 

```
3:17PM INF Replay last block using real app module=consensus
3:17PM INF finalized block block_app_hash=7096199951F524959607FC63BF39D16995351917F719201F5A639EBC96B45E31 height=66128 module=consensus num_txs_res=37 num_val_updates=0
3:17PM INF executed block app_hash=7096199951F524959607FC63BF39D16995351917F719201F5A639EBC96B45E31 height=66128 module=consensus
3:13PM INF Closing application.db module=server
3:13PM INF Closing snapshots/metadata.db module=server
panic: version does not exist
goroutine 1 [running]:
cosmossdk.io/store/iavl.(*Store).Commit(0xc003ef9440?)
	cosmossdk.io/store@v1.0.2/iavl/store.go:127 +0xd4
cosmossdk.io/store/rootmulti.commitStores(0x10250, 0xc003e671d0, 0xc04eb0a878?)
	cosmossdk.io/store@v1.0.2/rootmulti/store.go:1196 +0x14e
cosmossdk.io/store/rootmulti.(*Store).Commit(0xc002346000)
	cosmossdk.io/store@v1.0.2/rootmulti/store.go:482 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0022f9440)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:930 +0x2e2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:56
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0xc0013a2d20?, {0x3b4daa8?, 0x59e54a0?}, 0xc04eb0bbc8?)
	github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:113 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc0034e65e8, {0x3b4daa8, 0x59e54a0})
	github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:109 +0x165
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc0034785b0, 0x6}}, {0xc0034785b6, 0xa}, 0x1, 0x10250, {{0xc002d1f320, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/state/execution.go:393 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0034785b0, 0x6}}, {0xc0034785b6, 0xa}, 0x1, 0x10250, {{0xc002d1f320, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/state/execution.go:279 +0x1050
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0034785b0, 0x6}}, {0xc0034785b6, 0xa}, 0x1, 0x1024f, {{0xc0040a5580, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:534 +0x257
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc0034785b0, 0x6}}, {0xc0034785b6, 0xa}, 0x1, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:433 +0x79a
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc04eb0d3b0, {0x3b4da00, 0xc0025e0f00}, {0x3b6c3d0?, 0xc001f6e460?})
	github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x478
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc0034785b0, 0x6}}, {0xc0034785b6, 0xa}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x3b4da00, 0xc0025e0f00}, 0xc0016a88c0, {0x3b38760, 0xc003dfc000}, 0xc003e260e0, {0x3b11920, 0xc0036ae3a8}, 0x3c?, 0x355c7f8, ...)
	github.com/cometbft/cometbft@v0.38.5/node/node.go:350 +0x5b7
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x3b4da00, 0xc0025e0f00}, 0xc0016a88c0, {0x3b8e200?, 0xc00126a600}, 0xc0013a3ca0)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:402 +0x43f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc002343400, 0xb}, 0x0, {0xc002343820, 0x7}, {0x32d15b7, 0x1}, {0x32d15b7, 0x1}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:348 +0x188
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x3b702b8, 0xc001a27590}, 0x0, {0x0, 0x0}, {0x3b8e2c8, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:266 +0x2f3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:175 +0x5e
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc0013a3ca0, 0xc00124f810)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:600 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc0022ef300?, {0xc001b9b050?, 0x0?, 0x1?})
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:174 +0x212
github.com/spf13/cobra.(*Command).execute(0xc001758900, {0xc001b9b030, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0022c3200)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00128ff30?, {0x0, 0x0}, {0xc0006d39e0, 0xf})
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmd/execute.go:34 +0x187
main.main()
	github.com/babylonchain/babylon/cmd/babylond/main.go:18 +0x38
Error: exit status 2
3:13PM ERR error="exit status 2" module=cosmovisor
babylon.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by vitsalis** [comment]
If you can't boot up, please do `babylond rollback --hard`. Wait for it to complete and don't exit the command even if it takes for too long.

Regarding the issue initially specified by this issue, it seems to have been resolved. Probably node rejected the connection due to high load.
