### ISSUE TITLE
ERR failure when running app err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"

### ISSUE THREAD

**Issue by flxc11** [babylonchain/babylon#526]
My node's status was running, but when I tty to execute command "babylond status | jq" for view sync status, there was some error with:ERR failure when running app err="post failed: Post \"http://localhost:26657\": dial tcp 127.0.0.1:26657: connect: connection refused"

So, what can I do whti this error,please help me ,thanks.

**Comment by vitsalis** [comment]
You need to specify the host in which your RPC server is running through the `--node` command.

**Comment by flxc11** [comment]
> You need to specify the host in which your RPC server is running through the `--node` command.

Where can I find the RPC server?
