### ISSUE TITLE
block catch_up so slowly

### ISSUE THREAD

**Issue by isunfox** [babylonchain/babylon#527]
my node's height up to 48000,after block catch_up so slowly
It's up to 62000 for 3days
the version is :dev-107ab1b457f7b4caef846239990fc93a23efe96a

**Comment by isunfox** [comment]
![image](https://github.com/babylonchain/babylon/assets/30688978/33f603be-78f7-4a24-bc36-d933300a8b3b)

**Comment by vitsalis** [comment]
This was a known issue with the latest testnet, it should be resolved in future versions.
