### ISSUE TITLE
Phase1 -> Phase2

### ISSUE THREAD

**Issue by RafilxTenfen** [babylonchain/babylon#539]
Babylon plans to have 2 phases for launch on the next testnet 

**Phase-1** consists of having __NO__ Babylon blockchain running, only finality providers that wish to be at the start of the chain on the next phase. By having finality providers, it also allows users to stake their BTC to build up TVL, and then when the start of the Babylon chain happens it already starts with enough BTC locked to mitigate the attack scenario where someone with a lot of BTC could hijack the checkpoint at the beginning by having one malicious finality provider with 66%+ of all BTC locked.

**Phase-2** starts the Babylon blockchain with the finality providers and locked BTC previously created in phase-1. This way the finality providers at the start of the chain on the genesis block will already be created and have BTC delegations from all the users who believe in them. 

- Goal: Start the Babylon chain with Finality Providers and their BTC Delegations already locked in the BTC chain.
- To be able to start with some BTC delegations we need to have this data set on `GenesisState` and a few modules couldn't start with a modified state 
    > Currently most of the modules only had export/import of parameters
- After adding the genesis state import and export for the modules (`finality`, `btclightclient`, `btcstaking`), one script could be created that starts a Babylon Chain from scratch, creates a finality provider and delegates BTC to it, export the genesis from that chain, gather the information and manually modifies the initial genesis by adding BTC delegation, finality providers and BTC headers to an empty genesis block and starts a new chain from block zero with the new modified genesis (that contains the BTC headers, BTC delegations and Finality providers).

- For this to be accomplished, it could be divided into a few issues:
## Mandatory
- [x] #549 
- [x] #558
- [x] #570 
- [x] #584 
- [x] #585
- [x] #586
 
## Nice to Have for testnet
- [x] #600 
- [x] #556
- [x] #566
- [x] #569
- [x] #580
- [x] #583 

## Mainnet
- [x] #581

**Comment by puneet2019** [comment]
I believe BTC checkpointing module genesis also needs to be fixed? 
`Submision Store` should be added

**Comment by puneet2019** [comment]
oh. I just meant ... `Import / Export GenState` of BTC checkpointing module.. @RafilxTenfen

**Comment by RafilxTenfen** [comment]
Goal changed
