### ISSUE TITLE
ERR panic recovered in runTx err="out of gas in location: WritePerByte; gasWanted: 108242, gasUsed: 109517: out of gas" module=server

### ISSUE THREAD

**Issue by flxc11** [babylonchain/babylon#540]
When I running the node, there was some error:ERR panic recovered in runTx err="out of gas in location: WritePerByte; gasWanted: 108242, gasUsed: 109517: out of gas" module=server

So,how can I do with this error?

**Comment by vitsalis** [comment]
It seems that there was a transaction with not enough gas. Closing as this refers to a previous testnet and difficult to reproduce with the details provided.
