### ISSUE TITLE
[FULL_NODE] Memory usage (RAM) increasing exponentially starting 60k block height

### ISSUE THREAD

**Issue by 0xgasleft** [babylonchain/babylon#542]
## Summary of Bug

RAM Usage growing exponentially on node synchronizing.

## Version

Saw this behavior with:

- Babylon built from source tagged at: v0.8.3 & also v0.8.4
- Go-lang version at 1.21.8 & also 1.22.1(latest)
- Chain id: bbn-test-3

## Steps to Reproduce

1) Running a node following Babylon official doc on a 32 GB of RAM VPS.
2) Wait for node to reach ~60_000 block height
3) Start monitoring RAM usage, increasing exponentially by 1 GB for around 1000 blocks as of my observation
4) Operating system cuts off node when reaching max RAM (30 free GB in my case) which leads to panic exceptions in Babylon.

**Comment by trankil123** [comment]
i have the same issue

**Comment by vitsalis** [comment]
This is a known issue of testnet-3 which should be resolved in the next release. Thank you.
