### ISSUE TITLE
Unajail validator not found

### ISSUE THREAD

**Issue by cougarmaster** [babylonchain/babylon#543]
I am trying to unjail but it keeps saying my validator does not exist

TXID : 8FA44C12D83195A1AFCA75ACED968CEA9F9BC4E37D2A5040E408C3AEA11BBB51

The validator runs also the validator is not on Active Set but it didn't happen before. I upgraded to v0.8.4 and this happened. Did I lose the validator and need to create a new one? And if so can I use the same wallet address?

**Comment by vitsalis** [comment]
Not sure what command you executed. Closing as this relates to testnet-3 which has been sunsetted for quite some time.
