### ISSUE TITLE
Checking validator returns "Ooops! SOMETHING WENT WRONG" 

### ISSUE THREAD

**Issue by kevinhouge** [babylonchain/babylon#601]
## Summary of Bug
Checking validator returns "Ooops! SOMETHING WENT WRONG" on  https://babylon.explorers.guru/validators.

## Version
beta v.0.321.084

## Steps to Reproduce
1. Setup and run a Babylon Node 
2. After the validator is created, open  https://babylon.explorers.guru/validators and input the Moniker name 
3. Check if the validator can be retrieved successfully. However, you can see the following error: 

Ooops!
SOMETHING WENT WRONG

We are working hard to fix it

Try again later
<img width="932" alt="image" src="https://github.com/babylonchain/babylon/assets/141470573/11f262a9-39ce-49b1-9484-9686298fd45c">

**Comment by vitsalis** [comment]
This relates to the nodes.guru explorer and not this repository.
