### ISSUE TITLE
Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by deaabie** [babylonchain/babylon#602]
1:56PM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
1:56PM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
1:56PM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
1:56PM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
1:56PM INF service start impl=EventBus module=events msg="Starting EventBus service"
1:56PM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
1:56PM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
1:56PM INF ABCI Handshake App Info hash=216D90610628EF1A8AE534A2FEDAE81E237F47D6A363A2FC6EA2A59152DE155D height=139608 module=consensus protocol-version=0 software-version=v0.8.5
1:56PM INF ABCI Replay Blocks appHeight=139608 module=consensus stateHeight=139608 storeHeight=139609
1:56PM INF Replay last block using real app module=consensus
1:57PM INF finalized block block_app_hash=9F5EE7AAB7CD3891B19DE704032EF148733B150F0628A031A11F68504C7A8EEA height=139609 module=consensus num_txs_res=69 num_val_updates=0
1:57PM INF executed block app_hash=9F5EE7AAB7CD3891B19DE704032EF148733B150F0628A031A11F68504C7A8EEA height=139609 module=consensus
1:57PM INF Closing application.db module=server
1:57PM INF Closing snapshots/metadata.db module=server
panic: version does not exist
goroutine 1 [running]:
cosmossdk.io/store/iavl.(*Store).Commit(0xc001b136b0?)
        cosmossdk.io/store@v1.0.2/iavl/store.go:127 +0xd4
cosmossdk.io/store/rootmulti.commitStores(0x22159, 0xc002f10120, 0xc042c1a878?)
        cosmossdk.io/store@v1.0.2/rootmulti/store.go:1196 +0x14e
cosmossdk.io/store/rootmulti.(*Store).Commit(0xc002590000)
        cosmossdk.io/store@v1.0.2/rootmulti/store.go:482 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0006c4d80)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:930 +0x2e2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:56
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0xc003009900?, {0x3b582a8?, 0x59f0420?}, 0xc042c1bbc8?)
        github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:113 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc0015959e0, {0x3b582a8, 0x59f0420})
        github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:109 +0x165
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000c66da0, 0x6}}, {0xc000c66da6, 0xa}, 0x1, 0x22159, {{0xc001f911e0, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/state/execution.go:393 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000c66da0, 0x6}}, {0xc000c66da6, 0xa}, 0x1, 0x22159, {{0xc001f911e0, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/state/execution.go:279 +0x1050
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000c66da0, 0x6}}, {0xc000c66da6, 0xa}, 0x1, 0x22158, {{0xc00307b1a0, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:534 +0x257
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc000c66da0, 0x6}}, {0xc000c66da6, 0xa}, 0x1, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:433 +0x79a
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc042c1d3b0, {0x3b58200, 0xc003277bd0}, {0x3b76bd0?, 0xc00066dce0?})
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x478
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc000c66da0, 0x6}}, {0xc000c66da6, 0xa}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x3b58200, 0xc003277bd0}, 0xc0016a0b40, {0x3b42f60, 0xc002060b40}, 0xc00217d200, {0x3b1c120, 0xc00126b5c0}, 0x3c?, 0x3566d78, ...)
        github.com/cometbft/cometbft@v0.38.5/node/node.go:350 +0x5b7
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x3b58200, 0xc003277bd0}, 0xc0016a0b40, {0x3b98a00?, 0xc000b18600}, 0xc001ec5d60)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:402 +0x43f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc001a37580, 0xb}, 0x0, {0xc001a379a0, 0x6}, {0xc001a37f88, 0x3}, {0x33d0370, 0x2}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:348 +0x188
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x3b7aab8, 0xc001d84540}, 0x0, {0xc0015f10d0, 0xa}, {0x3b98ac8, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:266 +0x2f3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:175 +0x5e
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc001ec5d60, 0xc00111f810)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:600 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc001a8c700?, {0x59f0420?, 0x0?, 0x0?})
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:174 +0x212
github.com/spf13/cobra.(*Command).execute(0xc0012e4000, {0x59f0420, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000daaf00)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00111ff30?, {0x0, 0x0}, {0xc0010490d0, 0xf})
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmd/execute.go:34 +0x187
main.main()
        github.com/babylonchain/babylon/cmd/babylond/main.go:18 +0x38
babylond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
babylond.service: Failed with result 'exit-code'.
babylond.service: Scheduled restart job, restart counter is at 1.

anyone can help please ?

**Comment by nuuneoi** [comment]
Having the same issue here

**Comment by deaabie** [comment]
its solved yesterday.

**Comment by pil2776** [comment]
How do you solved it ?

**Comment by nuuneoi** [comment]
> How do you solved it ?

I reinstalled the whole thing, and it was resolved.

**Comment by halink0803** [comment]
> I reinstalled the whole thing, and it was resolved.

it means you have to sync from start?
