### ISSUE TITLE
FpBtcPkList Tampering Risk ?

### ISSUE THREAD

**Issue by tpkeeper** [babylonchain/babylon#638]
https://github.com/babylonchain/babylon/blob/f35c9b1509ef571ae4cfe8a95d9b0ef6b20d5586/x/btcstaking/keeper/msg_server.go#L198

There is no check whether it is the FpBtcPkList selected by the user.

**Comment by vitsalis** [comment]
This relates to the staker choosing multiple finality providers in the case of multi-staking which is planned for phase-3. Given that the staker is the signer of the request, they select which finality providers to delegate to.
