### ISSUE TITLE
`x/checkpointing` Add check to verify if Validator BLS key match on `WrappedCreateValidator`

### ISSUE THREAD

**Issue by RafilxTenfen** [babylonchain/babylon#640]
Make sure the BLS pub key matches the validator addr to avoid having one key for validator and another for BLS creation

Check on genesis init as well

**Comment by fuleru** [comment]
Please tell me how to do this. For example, the node restores the wallet through the mnemonic phrase.

**Comment by RafilxTenfen** [comment]
moved https://github.com/babylonlabs-io/babylon/issues/165
