### ISSUE TITLE
Cancel Delegate to yourself

### ISSUE THREAD

**Issue by fuleru** [babylonchain/babylon#644]
Delegate to yourself

```
babylond tx staking delegate $(babylond keys show wallet --bech val -a) 1000000ubbn --from wallet --chain-id bbn-test-3 --gas-prices 0.00001ubbn --gas-adjustment 1.5 --gas auto -y 
```

What command is used to remove Delegate to yourself?

## Version

git branch
* (HEAD detached at v0.8.5)

**Comment by vitsalis** [comment]
Please check the details of how we wrap the staking module with the epoching module and the messages associated with staking [here](https://github.com/babylonlabs-io/babylon/tree/main/x/epoching).
