### ISSUE TITLE
please upgrade the maximium staking cap in testnet 

### ISSUE THREAD

**Issue by wnhedaxx** [babylonchain/babylon#665]
Staking is temporarily disabled due to the staking cap getting reached.....

please upgrade the maximum staking cap from 50 Signet BTC to 100 Signet BTC.

![image](https://github.com/babylonchain/babylon/assets/70830772/b03180fd-a843-4c12-be4c-863b3e398e7b)

**Comment by vitsalis** [comment]
Closing as unrelated to the repository.
